name: Generate Datas

on:
  schedule: # Execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Animação Snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: vinisique
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output # Corrigido de target-branch para target_branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
